// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AgentDefaultOptions() {
  return window['go']['wails_api']['API']['AgentDefaultOptions']();
}

export function AgentDefaults() {
  return window['go']['wails_api']['API']['AgentDefaults']();
}

export function AgentStatuses() {
  return window['go']['wails_api']['API']['AgentStatuses']();
}

export function AnswerApproval(arg1, arg2, arg3, arg4) {
  return window['go']['wails_api']['API']['AnswerApproval'](arg1, arg2, arg3, arg4);
}

export function AnswerTaskAcceptance(arg1, arg2) {
  return window['go']['wails_api']['API']['AnswerTaskAcceptance'](arg1, arg2);
}

export function AuthAgent(arg1) {
  return window['go']['wails_api']['API']['AuthAgent'](arg1);
}

export function AuthorizeMCPServer(arg1) {
  return window['go']['wails_api']['API']['AuthorizeMCPServer'](arg1);
}

export function Autopilot() {
  return window['go']['wails_api']['API']['Autopilot']();
}

export function CancelSession(arg1) {
  return window['go']['wails_api']['API']['CancelSession'](arg1);
}

export function ChooseDirectory(arg1) {
  return window['go']['wails_api']['API']['ChooseDirectory'](arg1);
}

export function ChooseFile(arg1, arg2) {
  return window['go']['wails_api']['API']['ChooseFile'](arg1, arg2);
}

export function ChooseSaveFile(arg1, arg2, arg3) {
  return window['go']['wails_api']['API']['ChooseSaveFile'](arg1, arg2, arg3);
}

export function CompleteOnboarding() {
  return window['go']['wails_api']['API']['CompleteOnboarding']();
}

export function DeleteSessionDraft(arg1) {
  return window['go']['wails_api']['API']['DeleteSessionDraft'](arg1);
}

export function ExportTemplates(arg1, arg2) {
  return window['go']['wails_api']['API']['ExportTemplates'](arg1, arg2);
}

export function ImportTemplates(arg1) {
  return window['go']['wails_api']['API']['ImportTemplates'](arg1);
}

export function InstallAgent(arg1) {
  return window['go']['wails_api']['API']['InstallAgent'](arg1);
}

export function MCPServers() {
  return window['go']['wails_api']['API']['MCPServers']();
}

export function Onboarded() {
  return window['go']['wails_api']['API']['Onboarded']();
}

export function PendingApprovals() {
  return window['go']['wails_api']['API']['PendingApprovals']();
}

export function RefineTemplate(arg1) {
  return window['go']['wails_api']['API']['RefineTemplate'](arg1);
}

export function RemoveTemplate(arg1) {
  return window['go']['wails_api']['API']['RemoveTemplate'](arg1);
}

export function ResumeSession(arg1) {
  return window['go']['wails_api']['API']['ResumeSession'](arg1);
}

export function RetrySessionTask(arg1) {
  return window['go']['wails_api']['API']['RetrySessionTask'](arg1);
}

export function RevertSessionTo(arg1, arg2) {
  return window['go']['wails_api']['API']['RevertSessionTo'](arg1, arg2);
}

export function RevokeMCPServer(arg1) {
  return window['go']['wails_api']['API']['RevokeMCPServer'](arg1);
}

export function RunSession(arg1) {
  return window['go']['wails_api']['API']['RunSession'](arg1);
}

export function SaveSessionDraft(arg1, arg2) {
  return window['go']['wails_api']['API']['SaveSessionDraft'](arg1, arg2);
}

export function SessionDrafts() {
  return window['go']['wails_api']['API']['SessionDrafts']();
}

export function SessionStatus(arg1) {
  return window['go']['wails_api']['API']['SessionStatus'](arg1);
}

export function SetAgentDefault(arg1, arg2, arg3) {
  return window['go']['wails_api']['API']['SetAgentDefault'](arg1, arg2, arg3);
}

export function SetAutopilot(arg1) {
  return window['go']['wails_api']['API']['SetAutopilot'](arg1);
}

export function SetMCPCredential(arg1, arg2) {
  return window['go']['wails_api']['API']['SetMCPCredential'](arg1, arg2);
}

export function Shutdown(arg1) {
  return window['go']['wails_api']['API']['Shutdown'](arg1);
}

export function Startup(arg1) {
  return window['go']['wails_api']['API']['Startup'](arg1);
}

export function SubmitAuthCode(arg1, arg2) {
  return window['go']['wails_api']['API']['SubmitAuthCode'](arg1, arg2);
}

export function TaskDiff(arg1, arg2) {
  return window['go']['wails_api']['API']['TaskDiff'](arg1, arg2);
}

export function Template(arg1) {
  return window['go']['wails_api']['API']['Template'](arg1);
}

export function TemplateHelperBlocked() {
  return window['go']['wails_api']['API']['TemplateHelperBlocked']();
}

export function Templates() {
  return window['go']['wails_api']['API']['Templates']();
}

export function UninstallAgent(arg1) {
  return window['go']['wails_api']['API']['UninstallAgent'](arg1);
}

export function UpsertTemplate(arg1) {
  return window['go']['wails_api']['API']['UpsertTemplate'](arg1);
}
