// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AgentContextUsage(arg1) {
  return window['go']['wails_api']['API']['AgentContextUsage'](arg1);
}

export function AgentDefaultOptions() {
  return window['go']['wails_api']['API']['AgentDefaultOptions']();
}

export function AgentDefaults() {
  return window['go']['wails_api']['API']['AgentDefaults']();
}

export function AgentStatuses() {
  return window['go']['wails_api']['API']['AgentStatuses']();
}

export function AnswerApproval(arg1, arg2, arg3, arg4) {
  return window['go']['wails_api']['API']['AnswerApproval'](arg1, arg2, arg3, arg4);
}

export function AuthAgent(arg1) {
  return window['go']['wails_api']['API']['AuthAgent'](arg1);
}

export function InstallAgent(arg1) {
  return window['go']['wails_api']['API']['InstallAgent'](arg1);
}

export function KillAgent(arg1, arg2) {
  return window['go']['wails_api']['API']['KillAgent'](arg1, arg2);
}

export function PendingApprovals() {
  return window['go']['wails_api']['API']['PendingApprovals']();
}

export function RemoveTemplate(arg1) {
  return window['go']['wails_api']['API']['RemoveTemplate'](arg1);
}

export function RetrySessionTask(arg1) {
  return window['go']['wails_api']['API']['RetrySessionTask'](arg1);
}

export function RunSession(arg1) {
  return window['go']['wails_api']['API']['RunSession'](arg1);
}

export function SendToAgent(arg1, arg2, arg3) {
  return window['go']['wails_api']['API']['SendToAgent'](arg1, arg2, arg3);
}

export function SessionStatus(arg1) {
  return window['go']['wails_api']['API']['SessionStatus'](arg1);
}

export function SetAgentDefault(arg1, arg2, arg3) {
  return window['go']['wails_api']['API']['SetAgentDefault'](arg1, arg2, arg3);
}

export function Shutdown(arg1) {
  return window['go']['wails_api']['API']['Shutdown'](arg1);
}

export function SpawnAgent(arg1) {
  return window['go']['wails_api']['API']['SpawnAgent'](arg1);
}

export function Startup(arg1) {
  return window['go']['wails_api']['API']['Startup'](arg1);
}

export function SubmitAuthCode(arg1, arg2) {
  return window['go']['wails_api']['API']['SubmitAuthCode'](arg1, arg2);
}

export function Template(arg1) {
  return window['go']['wails_api']['API']['Template'](arg1);
}

export function Templates() {
  return window['go']['wails_api']['API']['Templates']();
}

export function UninstallAgent(arg1) {
  return window['go']['wails_api']['API']['UninstallAgent'](arg1);
}

export function UpsertTemplate(arg1) {
  return window['go']['wails_api']['API']['UpsertTemplate'](arg1);
}
