// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {output_itf} from '../models';
import {context} from '../models';

export function AgentDefaultOptions():Promise<output_itf.AgentDefaultOptionsInfo>;

export function AgentDefaults():Promise<Array<output_itf.AgentDefaultInfo>>;

export function AgentStatuses():Promise<Array<output_itf.AgentInfo>>;

export function AnswerApproval(arg1:string,arg2:boolean,arg3:Array<string>,arg4:string):Promise<void>;

export function AnswerTaskAcceptance(arg1:string,arg2:boolean):Promise<void>;

export function AuthAgent(arg1:string):Promise<string>;

export function AuthorizeMCPServer(arg1:string):Promise<void>;

export function Autopilot():Promise<boolean>;

export function CancelSession(arg1:string):Promise<void>;

export function ChooseDirectory(arg1:string):Promise<string>;

export function ChooseFile(arg1:string,arg2:string):Promise<string>;

export function ChooseSaveFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function CompleteOnboarding():Promise<void>;

export function DeleteSessionDraft(arg1:string):Promise<void>;

export function ExportTemplates(arg1:Array<string>,arg2:string):Promise<number>;

export function ImportTemplates(arg1:string):Promise<number>;

export function InstallAgent(arg1:string):Promise<void>;

export function MCPServers():Promise<Array<output_itf.MCPServerInfo>>;

export function Onboarded():Promise<boolean>;

export function PendingApprovals():Promise<Array<output_itf.ApprovalInfo>>;

export function RemoveTemplate(arg1:string):Promise<void>;

export function ResumeSession(arg1:string):Promise<void>;

export function RetrySessionTask(arg1:string):Promise<void>;

export function RevertSessionTo(arg1:string,arg2:string):Promise<void>;

export function RevokeMCPServer(arg1:string):Promise<void>;

export function RunSession(arg1:output_itf.RunSessionSpec):Promise<output_itf.RunSessionResult>;

export function SaveSessionDraft(arg1:string,arg2:string):Promise<void>;

export function SessionDrafts():Promise<Array<output_itf.SessionDraftInfo>>;

export function SessionStatus(arg1:string):Promise<output_itf.SessionStatusInfo>;

export function SetAgentDefault(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetAutopilot(arg1:boolean):Promise<void>;

export function SetMCPCredential(arg1:string,arg2:string):Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function SubmitAuthCode(arg1:string,arg2:string):Promise<void>;

export function TaskDiff(arg1:string,arg2:string):Promise<Array<output_itf.FileChangeInfo>>;

export function Template(arg1:string):Promise<output_itf.TemplateInfo>;

export function Templates():Promise<Array<output_itf.TemplateInfo>>;

export function UninstallAgent(arg1:string):Promise<void>;

export function UpsertTemplate(arg1:output_itf.TemplateInfo):Promise<string>;
