// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {output_itf} from '../models';
import {core_itf} from '../models';
import {context} from '../models';

export function AgentDefaultOptions():Promise<output_itf.AgentDefaultOptionsInfo>;

export function AgentDefaults():Promise<Array<output_itf.AgentDefaultInfo>>;

export function AgentStatuses():Promise<Array<output_itf.AgentInfo>>;

export function AnswerApproval(arg1:string,arg2:boolean,arg3:Array<string>,arg4:string):Promise<void>;

export function AnswerStepReview(arg1:string,arg2:boolean):Promise<void>;

export function AuthAgent(arg1:string):Promise<string>;

export function AuthorizeMCPServer(arg1:string):Promise<void>;

export function Autopilot():Promise<boolean>;

export function CancelWorkflow(arg1:string):Promise<void>;

export function ChooseDirectory(arg1:string):Promise<string>;

export function ChooseFile(arg1:string,arg2:string):Promise<string>;

export function ChooseSaveFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function CompleteOnboarding():Promise<void>;

export function DeleteWorkflowDraft(arg1:string):Promise<void>;

export function DiscardWorkflowRun(arg1:string):Promise<void>;

export function ExportRoles(arg1:Array<string>,arg2:string):Promise<number>;

export function ExportWorkflow(arg1:string,arg2:string):Promise<void>;

export function ImportRoles(arg1:string):Promise<number>;

export function ImportWorkflow(arg1:string):Promise<string>;

export function InstallAgent(arg1:string):Promise<void>;

export function Language():Promise<string>;

export function LogoutAgent(arg1:string):Promise<void>;

export function MCPServers():Promise<Array<output_itf.MCPServerInfo>>;

export function MaxRunningAgents():Promise<number>;

export function ModelPrices():Promise<Array<output_itf.ModelPriceInfo>>;

export function Onboarded():Promise<boolean>;

export function PauseWorkflow(arg1:string):Promise<void>;

export function PendingApprovals():Promise<Array<output_itf.ApprovalInfo>>;

export function RefineRole(arg1:core_itf.DraftRequest):Promise<output_itf.RoleInfo>;

export function RemoveRole(arg1:string):Promise<void>;

export function ResumeWorkflow(arg1:string):Promise<void>;

export function RetryWorkflowStep(arg1:string):Promise<void>;

export function RevertWorkflowTo(arg1:string,arg2:string):Promise<void>;

export function RevokeMCPServer(arg1:string):Promise<void>;

export function Role(arg1:string):Promise<output_itf.RoleInfo>;

export function RoleHelperBlocked():Promise<string>;

export function Roles():Promise<Array<output_itf.RoleInfo>>;

export function RunWorkflow(arg1:output_itf.RunWorkflowSpec):Promise<output_itf.RunWorkflowResult>;

export function SaveWorkflowDraft(arg1:string,arg2:string):Promise<void>;

export function SetAgentDefault(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetAutopilot(arg1:boolean):Promise<void>;

export function SetLanguage(arg1:string):Promise<void>;

export function SetMCPCredential(arg1:string,arg2:string):Promise<void>;

export function SetMaxRunningAgents(arg1:number):Promise<void>;

export function SetModelPrices(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function StepDiff(arg1:string,arg2:string):Promise<Array<output_itf.FileChangeInfo>>;

export function SubmitAuthCode(arg1:string,arg2:string):Promise<void>;

export function UninstallAgent(arg1:string):Promise<void>;

export function UpsertRole(arg1:output_itf.RoleInfo):Promise<string>;

export function WorkflowDrafts():Promise<Array<output_itf.WorkflowDraftInfo>>;

export function WorkflowStatus(arg1:string):Promise<output_itf.WorkflowStatusInfo>;
