// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {input_itf} from '../models';
import {output_itf} from '../models';
import {context} from '../models';

export function AgentContextUsage(arg1:string):Promise<input_itf.ContextUsage>;

export function AgentStatuses():Promise<Array<output_itf.AgentInfo>>;

export function AnswerApproval(arg1:string,arg2:boolean,arg3:Array<string>,arg4:string):Promise<void>;

export function AuthAgent(arg1:string):Promise<string>;

export function InstallAgent(arg1:string):Promise<void>;

export function KillAgent(arg1:string,arg2:string):Promise<void>;

export function PendingApprovals():Promise<Array<output_itf.ApprovalInfo>>;

export function RemoveTemplate(arg1:string):Promise<void>;

export function SendToAgent(arg1:string,arg2:string,arg3:string):Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function SpawnAgent(arg1:string):Promise<string>;

export function Startup(arg1:context.Context):Promise<void>;

export function SubmitAuthCode(arg1:string,arg2:string):Promise<void>;

export function Template(arg1:string):Promise<output_itf.TemplateInfo>;

export function Templates():Promise<Array<output_itf.TemplateInfo>>;

export function UninstallAgent(arg1:string):Promise<void>;

export function UpsertTemplate(arg1:output_itf.TemplateInfo):Promise<string>;
