// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AgentDefaultOptions() {
  return window['go']['wails_api']['API']['AgentDefaultOptions']();
}

export function AgentDefaults() {
  return window['go']['wails_api']['API']['AgentDefaults']();
}

export function AgentStatuses() {
  return window['go']['wails_api']['API']['AgentStatuses']();
}

export function AnswerApproval(arg1, arg2, arg3, arg4) {
  return window['go']['wails_api']['API']['AnswerApproval'](arg1, arg2, arg3, arg4);
}

export function AnswerStepReview(arg1, arg2) {
  return window['go']['wails_api']['API']['AnswerStepReview'](arg1, arg2);
}

export function AuthAgent(arg1) {
  return window['go']['wails_api']['API']['AuthAgent'](arg1);
}

export function AuthorizeMCPServer(arg1) {
  return window['go']['wails_api']['API']['AuthorizeMCPServer'](arg1);
}

export function Autopilot() {
  return window['go']['wails_api']['API']['Autopilot']();
}

export function CancelWorkflow(arg1) {
  return window['go']['wails_api']['API']['CancelWorkflow'](arg1);
}

export function ChooseDirectory(arg1) {
  return window['go']['wails_api']['API']['ChooseDirectory'](arg1);
}

export function ChooseFile(arg1, arg2) {
  return window['go']['wails_api']['API']['ChooseFile'](arg1, arg2);
}

export function ChooseSaveFile(arg1, arg2, arg3) {
  return window['go']['wails_api']['API']['ChooseSaveFile'](arg1, arg2, arg3);
}

export function CompleteOnboarding() {
  return window['go']['wails_api']['API']['CompleteOnboarding']();
}

export function DeleteWorkflowDraft(arg1) {
  return window['go']['wails_api']['API']['DeleteWorkflowDraft'](arg1);
}

export function DiscardWorkflowRun(arg1) {
  return window['go']['wails_api']['API']['DiscardWorkflowRun'](arg1);
}

export function ExportRoles(arg1, arg2) {
  return window['go']['wails_api']['API']['ExportRoles'](arg1, arg2);
}

export function ExportWorkflow(arg1, arg2) {
  return window['go']['wails_api']['API']['ExportWorkflow'](arg1, arg2);
}

export function ImportRoles(arg1) {
  return window['go']['wails_api']['API']['ImportRoles'](arg1);
}

export function ImportWorkflow(arg1) {
  return window['go']['wails_api']['API']['ImportWorkflow'](arg1);
}

export function InstallAgent(arg1) {
  return window['go']['wails_api']['API']['InstallAgent'](arg1);
}

export function Language() {
  return window['go']['wails_api']['API']['Language']();
}

export function LogoutAgent(arg1) {
  return window['go']['wails_api']['API']['LogoutAgent'](arg1);
}

export function MCPServers() {
  return window['go']['wails_api']['API']['MCPServers']();
}

export function MaxRunningAgents() {
  return window['go']['wails_api']['API']['MaxRunningAgents']();
}

export function ModelPrices() {
  return window['go']['wails_api']['API']['ModelPrices']();
}

export function Onboarded() {
  return window['go']['wails_api']['API']['Onboarded']();
}

export function PauseWorkflow(arg1) {
  return window['go']['wails_api']['API']['PauseWorkflow'](arg1);
}

export function PendingApprovals() {
  return window['go']['wails_api']['API']['PendingApprovals']();
}

export function RefineRole(arg1) {
  return window['go']['wails_api']['API']['RefineRole'](arg1);
}

export function RemoveRole(arg1) {
  return window['go']['wails_api']['API']['RemoveRole'](arg1);
}

export function ResumeWorkflow(arg1) {
  return window['go']['wails_api']['API']['ResumeWorkflow'](arg1);
}

export function RevertWorkflowTo(arg1, arg2) {
  return window['go']['wails_api']['API']['RevertWorkflowTo'](arg1, arg2);
}

export function RevokeMCPServer(arg1) {
  return window['go']['wails_api']['API']['RevokeMCPServer'](arg1);
}

export function Role(arg1) {
  return window['go']['wails_api']['API']['Role'](arg1);
}

export function RoleHelperBlocked() {
  return window['go']['wails_api']['API']['RoleHelperBlocked']();
}

export function Roles() {
  return window['go']['wails_api']['API']['Roles']();
}

export function RunWorkflow(arg1) {
  return window['go']['wails_api']['API']['RunWorkflow'](arg1);
}

export function SaveWorkflowDraft(arg1, arg2) {
  return window['go']['wails_api']['API']['SaveWorkflowDraft'](arg1, arg2);
}

export function SetAgentDefault(arg1, arg2, arg3) {
  return window['go']['wails_api']['API']['SetAgentDefault'](arg1, arg2, arg3);
}

export function SetAutopilot(arg1) {
  return window['go']['wails_api']['API']['SetAutopilot'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['wails_api']['API']['SetLanguage'](arg1);
}

export function SetMCPCredential(arg1, arg2) {
  return window['go']['wails_api']['API']['SetMCPCredential'](arg1, arg2);
}

export function SetMaxRunningAgents(arg1) {
  return window['go']['wails_api']['API']['SetMaxRunningAgents'](arg1);
}

export function SetModelPrices(arg1, arg2, arg3, arg4) {
  return window['go']['wails_api']['API']['SetModelPrices'](arg1, arg2, arg3, arg4);
}

export function Shutdown(arg1) {
  return window['go']['wails_api']['API']['Shutdown'](arg1);
}

export function Startup(arg1) {
  return window['go']['wails_api']['API']['Startup'](arg1);
}

export function StepDiff(arg1, arg2) {
  return window['go']['wails_api']['API']['StepDiff'](arg1, arg2);
}

export function SubmitAuthCode(arg1, arg2) {
  return window['go']['wails_api']['API']['SubmitAuthCode'](arg1, arg2);
}

export function UninstallAgent(arg1) {
  return window['go']['wails_api']['API']['UninstallAgent'](arg1);
}

export function UpsertRole(arg1) {
  return window['go']['wails_api']['API']['UpsertRole'](arg1);
}

export function WorkflowDrafts() {
  return window['go']['wails_api']['API']['WorkflowDrafts']();
}

export function WorkflowStatus(arg1) {
  return window['go']['wails_api']['API']['WorkflowStatus'](arg1);
}
